"""Detect tape-regime transitions and emit an alert payload.

Compares today's tape regime to yesterday's (read from docs/daily/). When
the regime changes — especially HOSTILE → MIXED or MIXED → TRENDING —
emit a markdown body the GHA workflow can use to open a GitHub issue,
so the user gets a phone notification via GitHub Mobile.

Exit codes:
  0 — no transition (silent)
  1 — transition detected (workflow opens issue)
"""
from __future__ import annotations

import re
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path

from nse_backtest.data import fetch_nifty50
from nse_backtest.tape_monitor import assess_tape, TapeRegime

IST = timezone(timedelta(hours=5, minutes=30))
DAILY_DIR = Path("docs/daily")
OUT_PATH = Path("tape_flip_body.md")


def _previous_regime() -> tuple[str | None, str | None]:
    """Return (regime, date_str) of the most recent prior daily report, or None."""
    if not DAILY_DIR.exists():
        return None, None
    today_str = datetime.now(tz=IST).strftime("%Y-%m-%d")
    files = sorted(p for p in DAILY_DIR.glob("*.md") if p.stem < today_str)
    if not files:
        return None, None
    latest = files[-1]
    text = latest.read_text()
    # Regime line shape: "## 🔴 Today's regime: **HOSTILE**"
    m = re.search(r"Today's regime:\s*\*\*(\w+)\*\*", text)
    return (m.group(1) if m else None), latest.stem


def main() -> int:
    nifty = fetch_nifty50(start="2022-01-01")
    if nifty is None or len(nifty) < 200:
        print("Tape-flip check: insufficient Nifty data")
        return 0
    a = assess_tape(nifty)
    if a is None:
        return 0
    today_regime = a.regime
    today_str = datetime.now(tz=IST).strftime("%Y-%m-%d")
    prev_regime, prev_date = _previous_regime()
    if prev_regime is None:
        print(f"Tape-flip check: no prior report to compare against ({today_regime})")
        return 0
    if prev_regime == today_regime:
        print(f"Tape-flip check: regime unchanged ({today_regime}) since {prev_date}")
        return 0

    direction_emoji = {
        ("HOSTILE", "MIXED"):    "🟡 RECOVERING",
        ("HOSTILE", "TRENDING"): "🟢 BIG FLIP — go-time",
        ("MIXED", "TRENDING"):   "🟢 CONFIRMING TREND",
        ("MIXED", "HOSTILE"):    "🔴 DETERIORATING",
        ("TRENDING", "MIXED"):   "🟡 TREND COOLING",
        ("TRENDING", "HOSTILE"): "🔴 TREND BROKEN",
    }.get((prev_regime, today_regime), "🔁 REGIME CHANGE")

    rec_table = {
        TapeRegime.TRENDING: "Trade normally — top-3 picks ≥65, 2% risk.",
        TapeRegime.MIXED:    "Be selective — only score ≥75 with R:R ≥2.5.",
        TapeRegime.HOSTILE:  "Paper-trade only — sit out real money.",
    }
    body = f"""### {direction_emoji}

Tape regime flipped: **{prev_regime}** ({prev_date}) → **{today_regime}** ({today_str}).

| Metric | Value |
|---|---|
| Nifty close | ₹{a.nifty_close:,.2f} |
| 60-day return | {a.return_60d_pct:+.2f}% |
| Above 50-EMA | {"✅" if a.above_50ema else "❌"} |
| Above 200-EMA | {"✅" if a.above_200ema else "❌"} |
| Golden cross | {"✅" if a.ema_50_above_200 else "❌"} |
| 200-EMA 20d slope | {a.ema_200_slope_pct_20d:+.2f}% |

### What to do today

{rec_table.get(today_regime, '')}

Open the app: https://nse-trading-lab.streamlit.app (or your local `./start.sh`).
Today's full report: `docs/daily/{today_str}.md`.

_Auto-generated by `.github/workflows/tape-flip-alert.yml`._
"""
    OUT_PATH.write_text(body)
    print(f"FLIP DETECTED: {prev_regime} → {today_regime}")
    return 1


if __name__ == "__main__":
    sys.exit(main())
