"""Generate the two real snapshots that close out Phase 1.

Runs replay_picker on Nifty 50 over a date window, sorts trades by net_return_pct,
picks the two clearest winners (highest score-at-entry with positive net return),
and writes a human-readable markdown snapshot per trade.

Performance: full Nifty 50 × 3-year daily replay can exceed 10 minutes due to the
per-bar analyze_swing cost. Default settings replay 2024 with a 5-day stride
(weekly sampling) which gives plenty of GO picks for snapshot selection while
finishing in a couple of minutes. Override START/END/STRIDE env vars for full sweeps.
"""
import os
from pathlib import Path
import pandas as pd

from nse_backtest.data import fetch_multiple, NIFTY50_SYMBOLS
from nse_backtest.picker_replay import replay_picker

OUT_DIR = Path("output/snapshots")
OUT_DIR.mkdir(parents=True, exist_ok=True)

START = os.getenv("SNAPSHOT_START", "2024-01-01")
END = os.getenv("SNAPSHOT_END", "2024-12-31")
STRIDE_DAYS = int(os.getenv("SNAPSHOT_STRIDE", "5"))  # weekly by default
MIN_SCORE = float(os.getenv("SNAPSHOT_MIN_SCORE", "65"))
MAX_HOLD = int(os.getenv("SNAPSHOT_MAX_HOLD", "15"))


def stride_filter(symbol_data: dict, stride_days: int) -> dict:
    """Keep every Nth bar to reduce replay-runtime by N×.

    Stride is applied symmetrically across symbols so the date grid is consistent.
    """
    if stride_days <= 1:
        return symbol_data
    out = {}
    for sym, df in symbol_data.items():
        # Keep every Nth row by integer position; preserves index dtype.
        out[sym] = df.iloc[::stride_days].copy()
    return out


def main():
    print(f"Fetching Nifty 50 history (full daily bars from 2022-01-01)…")
    symbol_data = fetch_multiple(NIFTY50_SYMBOLS, start="2022-01-01")
    print(f"  → fetched {len(symbol_data)} symbols")

    if STRIDE_DAYS > 1:
        print(f"Applying stride={STRIDE_DAYS} (weekly sampling)…")
        sampled = stride_filter(symbol_data, STRIDE_DAYS)
    else:
        sampled = symbol_data

    print(f"Replaying {START} → {END} on sampled data (min_score={MIN_SCORE}, max_hold={MAX_HOLD})…")
    report = replay_picker(
        symbol_data=sampled,
        start=START, end=END,
        min_score=MIN_SCORE, max_hold=MAX_HOLD,
    )

    df = report.to_dataframe()
    csv_path = OUT_DIR / f"phase1_picker_replay_{START}_to_{END}.csv"
    df.to_csv(csv_path, index=False)
    print(f"Wrote {len(df)} trades to {csv_path}")

    if len(df) == 0:
        print("⚠️  Zero trades. Try lowering MIN_SCORE or widening the window.")
        # Still write an empty snapshot file so the deliverable exists.
        (OUT_DIR / "phase1_top_two.md").write_text(
            "# Phase 1 Snapshots\n\nReplay produced 0 GO picks for "
            f"{START}–{END} at min_score={MIN_SCORE}.\nRe-run with relaxed parameters.\n"
        )
        return

    # Pick top 2 by (score desc, then net% desc), preferring positive net%
    winners = df[df["net_%"] > 0].sort_values(
        by=["score", "net_%"], ascending=[False, False]
    ).head(2)

    if len(winners) < 2:
        print(f"⚠️  Only {len(winners)} winners — supplementing with top-net% regardless of sign.")
        winners = df.sort_values(by="net_%", ascending=False).head(2)

    lines = [f"# Phase 1 — Two Real Picker-Replay Snapshots (Nifty 50, {START} → {END})\n"]
    lines.append("Generated by `scripts/generate_snapshots.py` from `replay_picker`.")
    lines.append("Net returns are after Zerodha delivery costs (STT, stamp, GST, slippage, DP).\n")

    for i, (_, r) in enumerate(winners.iterrows(), 1):
        lines.append(f"## Snapshot {i} — {r['symbol']} ({r['entry_date']} → {r['exit_date']})\n")
        lines.append("```")
        lines.append(f"Engine verdict at entry: GO  ·  Score {r['score']}/100  ·  Win prob {r['win_prob']}%")
        lines.append(f"Entry         ₹{r['entry_price']:,.2f}")
        lines.append(f"Exit          ₹{r['exit_price']:,.2f}  ({r['exit_reason']})")
        lines.append(f"Held          {r['bars_held']} bars")
        lines.append(f"Gross return  {r['gross_%']:+.2f}%")
        lines.append(f"Net return    {r['net_%']:+.2f}%")
        lines.append("```")
        lines.append("")

    md_path = OUT_DIR / "phase1_top_two.md"
    md_path.write_text("\n".join(lines))
    print(f"Wrote {md_path}")

    print("\n--- Summary ---")
    print(f"Total trades : {len(df)}")
    print(f"Win rate     : {report.win_rate * 100:.1f}%")
    print(f"Avg win      : {report.avg_win_pct:+.2f}%")
    print(f"Avg loss     : {report.avg_loss_pct:+.2f}%")
    print(f"Expectancy   : {report.expectancy_pct:+.2f}%")
    print(f"Profit factor: {report.profit_factor:.2f}")


if __name__ == "__main__":
    main()
