"""Emit a daily tape regime report as markdown.

Designed to be invoked from a scheduled GitHub Action after Indian markets
close (12:30 UTC). Writes docs/daily/YYYY-MM-DD.md so the user wakes up to
a one-glance "what's the tape doing" view without launching the app.

Usage:
    PYTHONPATH=. python3 scripts/write_daily_tape_report.py
    PYTHONPATH=. python3 scripts/write_daily_tape_report.py --stdout

Exit codes:
    0  Report written (or printed) successfully.
    1  Data unavailable or tape assessment failed.
"""
from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path

from nse_backtest.data import fetch_nifty50
from nse_backtest.tape_monitor import assess_tape, TapeRegime
from components.data_freshness import check_freshness


IST = timezone(timedelta(hours=5, minutes=30))
DAILY_DIR = Path("docs/daily")


def _emoji_for(regime: str) -> str:
    return {
        TapeRegime.TRENDING: "🟢",
        TapeRegime.MIXED: "🟡",
        TapeRegime.HOSTILE: "🔴",
    }.get(regime, "⚪")


def build_report(now_ist: datetime) -> tuple[str, str] | None:
    """Returns (date_str, markdown) or None if data is unavailable."""
    nifty = fetch_nifty50(start="2022-01-01")
    if nifty is None or len(nifty) < 200:
        return None
    a = assess_tape(nifty)
    if a is None:
        return None
    f = check_freshness(nifty)

    date_str = now_ist.strftime("%Y-%m-%d")
    last_bar = nifty.index[-1].date().isoformat()
    emoji = _emoji_for(a.regime)

    hostile_triggers = []
    if not a.above_200ema:
        hostile_triggers.append("Nifty close below 200-EMA")
    if a.return_60d_pct < -3.0:
        hostile_triggers.append(f"60d return {a.return_60d_pct:+.2f}% < -3.0%")
    if a.ema_200_slope_pct_20d < -0.5:
        hostile_triggers.append(
            f"200-EMA slope {a.ema_200_slope_pct_20d:+.2f}%/20d < -0.5%"
        )

    md = f"""# Daily Tape Report — {date_str}

> Source: yfinance ^NSEI (Nifty 50 index), generated for IST date {date_str}.
> This file is committed automatically by the daily GitHub Action.

## {emoji} Today's regime: **{a.regime}**

| Metric | Value |
|---|---|
| Nifty close (last bar {last_bar}) | ₹{a.nifty_close:,.2f} |
| 60-day return | {a.return_60d_pct:+.2f}% |
| Above 50-EMA | {"✅" if a.above_50ema else "❌"} |
| Above 200-EMA | {"✅" if a.above_200ema else "❌"} |
| Golden cross (50-EMA > 200-EMA) | {"✅" if a.ema_50_above_200 else "❌"} |
| 200-EMA 20-day slope | {a.ema_200_slope_pct_20d:+.2f}% |
| Data freshness | {f.status} |

## Engine recommendation

{a.recommendation}

"""
    if a.regime == TapeRegime.HOSTILE and hostile_triggers:
        md += "## Why HOSTILE today\n\n"
        for t in hostile_triggers:
            md += f"- {t}\n"
        md += "\n"

    md += """## What to do tomorrow

| Regime | Action |
|---|---|
| 🟢 TRENDING | Trade normally — top-3 picks with score ≥65, 2% risk sizing |
| 🟡 MIXED    | Be selective — only score ≥75 with R:R ≥2.5 |
| 🔴 HOSTILE  | Paper-trade only — sit out real money |

---

_Auto-generated by `.github/workflows/daily-tape-report.yml`._
"""
    return date_str, md


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--stdout", action="store_true",
                   help="Print to stdout instead of writing to docs/daily/")
    args = p.parse_args()

    now_ist = datetime.now(tz=IST)
    result = build_report(now_ist)
    if result is None:
        print("ERROR: insufficient data to generate report", file=sys.stderr)
        return 1
    date_str, md = result

    if args.stdout:
        sys.stdout.write(md)
        return 0

    DAILY_DIR.mkdir(parents=True, exist_ok=True)
    out_path = DAILY_DIR / f"{date_str}.md"
    out_path.write_text(md)
    print(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
